Update: README.md
SamurAI-Coding/Software2017-18 pull request #9
Opened 2017-10-13 09:28 UTC by arukuka

add infomation to README.md

2017-12-29 09:09 UTC, arukuka commented
日本語版はこれで良さそうと委員会のご意見をいただいたので
これを元に英語版を作成します。

2017-12-31 08:51 UTC, tastasgit commented
英語版，元のままでも致命的な問題はないと思いましたが，表現等修正しておきました．
私はこれで問題ないと思います．

2017-12-31 08:52 UTC, arukuka commented
@tastasgit さん、校正ありがとうございます…

2017-12-31 11:41 UTC, kawatiya requested changes
A sample player executable can be build
-> can be built

2017-12-31 14:04 UTC, tastasgit commented
README.md の英文修正，およびkawatiyaさんのご指摘に対応しました

2017-12-31 15:14 UTC, arukuka commented
ありがとうございます。
これで merge します、

2017-12-31 15:16 UTC, merged

2018-01-01 00:35 UTC, washizaki commented
[this repo](https://github.com/SamurAI-Coding/Software2017-18) have software 
-> 
[this repo](https://github.com/SamurAI-Coding/Software2017-18) has software

2018-01-01 01:26 UTC, arukuka commented
@washizaki さん、ありがとうございます。
@tastasgit さんの修整で `have` 自体が変わっていて
`contains` になったので大丈夫そうです。

2018-01-01 02:02 UTC, washizaki commented
@arukuka その後の修正がありましたね、有難うございました。